# Generated by Django 4.0.2 on 2022-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tranfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.TextField(max_length=50)),
                ('blood_product_type', models.TextField(max_length=20)),
                ('blood_product_id', models.IntegerField()),
            ],
        ),
    ]
